### ISSUE TITLE
Studentenwerk Berlin completely changed Speiseplan structure

### ISSUE THREAD

**Issue by kaifabian** [kaifabian/om-parser-berlin#1]
Studentenwerk Berlin has updated their meal plans completely (new URL, now XHR requests with one page per date).

New requests go to https://www.stw.berlin/xhr/speiseplan-wochentag.html as POST request with two parameters:
- `resources_id`: numeric value representing the canteen
- `date`: 'YYYY-mm-dd' formatted date

Meal plans are available for current and next week.

**Comment by lenucksi** [comment]
The actual data is in 
- Food description: body > div:nth-child(4) > div:nth-child(3) > div.col-xs-6.col-md-6 > span
- Price: body > div:nth-child(4) > div:nth-child(3) > div.col-xs-6.col-md-3.text-right
- Group separator is in: body > div:nth-child(4) > div:nth-child(1) > div
(All "selector" definitions based on Chrome dev tools.)

**Comment by ekeih** [comment]
Hi,
I also wrote a parser for Studierendenwerk Berlin. It does not support the OpenMensa format but maybe it helps you with your implementation: https://github.com/ekeih/OmNomNom/blob/master/canteens/studierendenwerk.py
Best regards
Max

**Comment by kaifabian** [comment]
Thanks all for your efforts of bringing back Berlins canteens to OpenMensa! :)

As the new parser implementation will be maintained in https://github.com/mswart/openmensa-parsers, this issue is a "wontfix".

**Comment by kaifabian** [comment]
Forgot to close this one. This repo will be archived and redirect to [mswart/openmensa-parsers](/mswart/openmensa-parsers).
Edit: or redirect to [escrl/openmensa-parser-berlin](/escrl/openmensa-parser-berlin), as it seems like this is the new parser used on [openmensa.org](https://www.openmensa.org).
